version: 0.0
os: linux
files:
 - source: /
   destination: /var/www/html
hooks:
  AfterInstall:
  -location: install_apache.sh
   timeout: 300
  ApplicationStart:
  -location: start_apache.sh
   timeout: 300
